ChatCompletion(
    id='chatcmpl-ANZh9z8ELKZ8DiPBi9MUOoyA1ZqEJ', 
    choices=[
        Choice(
            finish_reason='stop', 
            index=0, 
            logprobs=None, 
            message=ChatCompletionMessage(
                content='Hi there! Are you looking to purchase a hat, or do you have an issue with a hat you already own?', 
                refusal=None, 
                role='assistant', 
                audio=None, 
                function_call=None, 
                tool_calls=None
            )
        )
    ], 
    created=1730182119, 
    model='gpt-4o-2024-08-06', 
    object='chat.completion', 
    service_tier=None, 
    system_fingerprint='fp_90354628f2', 
    usage=CompletionUsage(
        completion_tokens=25, 
        prompt_tokens=132, 
        total_tokens=157, 
        completion_tokens_details=CompletionTokensDetails(
            audio_tokens=None, 
            reasoning_tokens=0
        ), 
        prompt_tokens_details=PromptTokensDetails(
            audio_tokens=None, 
            cached_tokens=0
        )
    )
)